### ISSUE TITLE
commented out code

### ISSUE THREAD

**Issue by iantheninja** [adara-code/wikipage#2]
instead of leaving huge chunks of code commented out..please delete the code to have cleaner and more readable code

**Comment by adara-code** [comment]
This is  long overdue, my goodness. Am I still allowed to consult your services? :D I don't understand the issue you were raising.

**Comment by iantheninja** [comment]
hey @adara-code of course you can. The file i was talking about had huge chunks of code that was commented out and thus not useful in the page. Wanted you to get rid of such code. It makes you seem like an untidy programmer.

**Comment by adara-code** [comment]
Noted. Thanks for the feedback.
